// ASSIGNMENTS LIST 
export const GET_ASSIGNMENTS_LIST_SUCCESS = "GET_ASSIGNMENTS_LIST_SUCCESS";
export const GET_ASSIGNMENTS_LIST_FAIL = "GET_ASSIGNMENTS_LIST_FAIL";

// ASSIGNMENTS DETAIL 
export const GET_ASSIGNMENT_DETAIL_SUCCESS = "GET_ASSIGNMENT_DETAIL_SUCCESS";
export const GET_ASSIGNMENT_DETAIL_FAIL = "GET_ASSIGNMENT_DETAIL_FAIL";

// CREATE ASSIGNMENTS  
export const CREATE_ASSIGNMENT_SUCCESS = "CREATE_ASSIGNMENT_SUCCESS";
export const CREATE_ASSIGNMENT_FAIL = "CREATE_ASSIGNMENT_FAIL";

// CREATE GRADED ASSIGNMENTS  

export const GET_GRADED_ASSIGNMENTS_LIST_SUCCESS =
    "GET_GRADED_ASSIGNMENTS_LIST_SUCCESS";
export const GET_GRADED_ASSIGNMENTS_LIST_FAIL =
    "GET_GRADED_ASSIGNMENTS_LIST_FAIL";


    
export const CREATE_GRADED_ASSIGNMENTS_LIST_SUCCESS =
    "CREATE_GRADED_ASSIGNMENTS_LIST_SUCCESS";
export const CREATE_GRADED_ASSIGNMENTS_LIST_FAIL =
    "CREATE_GRADED_ASSIGNMENTS_LIST_FAIL";


    
    